---
kind: pipeline
name: test

trigger:
  ref:
    - refs/heads/master  # All pushes to master

    - refs/heads/drone    # All pushes to yarn

    - refs/pull/*/*      # All pull requests regardless of branch

    - refs/tags/*        # Tags for releasing/etc
 
platform:
  os: linux
  arch: amd64

workspace:
  base: /node

steps:
  - name: drone-react-build-tests
    image: node:10.16.3
    pull: default
    commands:
      - curl -o- -L https://yarnpkg.com/install.sh | bash
      - make test

  - name: notify-in-slack-tests
    image: plugins/slack
    pull: default
    when:
      status:
        - success
        - failure
    environment:
      SLACK_WEBHOOK:
        from_secret: SLACK_WEBHOOK
    settings:
      webhook: $SLACK_WEBHOOK
      channel: git-submits
      # Note that the extra new lines are for slack formatting
      template: >
        {{#success build.status}}
        TESTS PASSED
        {{else}}
        TESTS FAILED
        {{/success}}
        {{build.link}}

        Repo: {{repo.name}}

        Branch: {{build.branch}}
        
        Ref: {{build.ref}}

        Commit: {{build.commit}}

        Commit Author: {{build.author}}


---
kind: pipeline
name: build-and-push

depends_on:
  - test

trigger:
  status:
    - success           # Only run if the test pipeline exits successfully
  ref: 
    - refs/heads/master # Build the latest image of master on all pushes (tagged as latest)

    - refs/heads/drone # Build the latest image of master on all pushes (tagged as latest)

    - refs/tags/*       # Build when we tag for releases

platform:
  os: linux
  arch: amd64

workspace:
  base: /node

steps:
  - name: build
    image: node:10.16.3
    commands:
      - echo "machine github.com login drone-react-build password $GITHUB_ACCESS_TOKEN" >> $HOME/.netrc
      - curl -o- -L https://yarnpkg.com/install.sh | bash
      - make build-drone

  - name: build-push-docker  
    image: plugins/docker  # http://plugins.drone.io/drone-plugins/drone-docker/
    settings:
      repo: flavioespinoza/${DRONE_REPO_NAME}
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      auto_tag: true
      purge: true
      dockerfile: Dockerfile.release

  - name: notify-in-slack-build
    image: plugins/slack
    pull: default
    when:
      status:
        - success
        - failure
    environment:
      SLACK_WEBHOOK:
        from_secret: SLACK_WEBHOOK
    settings:
      webhook: $SLACK_WEBHOOK
      channel: git-submits
      # Note that the extra new lines are for slack formatting
      template: >
        {{#success build.status}}
        BUILD SUCCEEDED
        {{else}}
        BUILD FAILED
        {{/success}}
        {{build.link}}

        Repo: {{repo.name}}

        Branch: {{build.branch}}
        
        Ref: {{build.ref}}

        Commit: {{build.commit}}

        Commit Author: {{build.author}}
