# Base image
FROM node:10.16.3-alpine

COPY ./ 	/wsdev/authnet-app/

WORKDIR /wsdev/authnet-app

# Node ENV production
ENV NODE_ENV=production
ENV DOMAIN_ENV=pd
ENV CI=true

# Required for linux sass binary
RUN cd /wsdev/authnet-app && yarn run prebuild

# Create optimized build
RUN cd /wsdev/authnet-app && yarn run build

# Expose the port so host can have access
EXPOSE 80

CMD [ "yarn", "start-prod" ]