# Base image
FROM node:10.16.3-alpine

# Node env
ARG NODE_ENV=production
ENV NODE_ENV=$NODE_ENV

# Deployment working directory
WORKDIR /wsdev/app

# Copy the app in (node_modules must be already installed)
COPY ./  	/wsdev/app/

# Required for linux sass binary
RUN cd /wsdev/app && yarn run prebuild

# Expose internal port
EXPOSE 3030

CMD [ "yarn", "start-prod" ]